// packages/react/src/BocetoEdit.tsx
import { createElement, useEffect, useRef, type CSSProperties } from 'react'
import { defineBocetoEdit, type BocetoEditElement } from '@boceto/edit'

export interface BocetoEditProps {
  code?: string
  width?: number
  height?: number
  readOnly?: boolean
  className?: string
  style?: CSSProperties
  onChange?: (code: string) => void
}

export function BocetoEdit(props: BocetoEditProps): JSX.Element {
  const ref = useRef<BocetoEditElement | null>(null)

  useEffect(() => {
    defineBocetoEdit()
  }, [])

  useEffect(() => {
    const el = ref.current
    const onChange = props.onChange
    if (!el || !onChange) return
    const handler = (e: Event) => {
      const detail = (e as CustomEvent).detail as { code: string }
      onChange(detail.code)
    }
    el.addEventListener('change', handler)
    return () => el.removeEventListener('change', handler)
  }, [props.onChange])

  return createElement('boceto-edit', {
    ref,
    code: props.code,
    width: props.width,
    height: props.height,
    readonly: props.readOnly ? '' : undefined,
    class: props.className,
    style: props.style,
  })
}

// packages/svelte/src/BocetoEdit.svelte
<!--
  `<BocetoEdit>` — Svelte wrapper around the `<boceto-edit>` custom element.

  The element's native `change` CustomEvent is re-emitted as Svelte `on:change`,
  with the new code string surfaced both as `event.detail` and via a bind:code
  prop for two-way binding (`<BocetoEdit bind:code />`).
-->
<script>
  import { onMount, createEventDispatcher } from 'svelte'
  import { defineBocetoEdit } from '@boceto/edit'

  /** DSL source. Bindable for two-way sync (`bind:code`). */
  export let code = ''
  export let width = undefined
  export let height = undefined
  export let readOnly = false
  let className = ''
  export { className as class }
  export let style = undefined

  let el
  const dispatch = createEventDispatcher()

  onMount(() => {
    defineBocetoEdit()
  })

  $: if (el) {
    const handler = (e) => {
      code = e.detail.code
      dispatch('change', { code: e.detail.code })
    }
    el.addEventListener('change', handler)
  }
</script>

<boceto-edit
  bind:this={el}
  {code}
  {width}
  {height}
  readonly={readOnly ? '' : undefined}
  class={className}
  {style}
></boceto-edit>
